# Generated by Django 5.2.9 on 2026-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
