# Generated by Django 5.2.9 on 2026-01-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Students', '0002_student_details_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.course_details'),
        ),
    ]
