# Generated by Django 6.0.2 on 2026-04-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_enrollmentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
