# Generated by Django 5.2.9 on 2026-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_duration', models.IntegerField(help_text='Duration in days')),
            ],
        ),
    ]
